### ISSUE TITLE
Problem with data file  moubalagha.csv please replace

### ISSUE THREAD

**Issue by khashabawy** [linuxscout/arramooz#12]
There is a problem with data file  **moubalagha.csv** please replace.

Also the file **wordfreq.csv** , i can not generate the SQL file from it

Thank you for all of your efforts

**Comment by linuxscout** [comment]
Thanks for report.
I fixed it.

**Comment by khashabawy** [comment]
Thanks
Also the file wordfreq.csv , i can not generate the SQL file from it
