### ISSUE TITLE
Issue about building dictionary

### ISSUE THREAD

**Issue by FengYusheng** [linuxscout/arramooz#13]
Hi linuxscout,

I want to build a dictionary for hunspell. But I encountered an issue when I tried to build dictionary with `make` according to the README.md.
![image](https://user-images.githubusercontent.com/10497376/56716626-65e34480-676d-11e9-8ca7-85d820e4364d.png)

When I run `make spell`, I got this issue:
![image](https://user-images.githubusercontent.com/10497376/56717798-09355900-6770-11e9-828c-173c7422952b.png)

Do you have any suggestions?

Thanks

**Comment by linuxscout** [comment]
Salam Yusheng,
I am Taha,
I just update the repository and fix this errors.
thanks

**Comment by FengYusheng** [comment]
Thanks, Taha,
I can build the dictionary now. These are my steps of building Hunspell dictionary:
1. `make`
2. `make spell`

I have an additional question about  **nouns.dict.spell**  after building dictionary files. I'm not familiar with Hunspell dictionary format, but I guess these lines shouldn't appear in  **nouns.dict.spell**. They look like python source codes.

 
![图片](https://user-images.githubusercontent.com/10497376/56861460-7bf23e80-69d3-11e9-8e5b-484ba3ad2f59.png)

Thanks again,  “万事如意”
Yusheng

**Comment by linuxscout** [comment]
Salam Yusheng,
Thanks you, I just use a debug print suffixes list,
I updated the script .
thanks,
If you want build Hunspell dictionary, you can take a look on [Ayaspell](https://github.com/linuxscout/ayaspell).

**Comment by FengYusheng** [comment]
Thanks, Taha,

I close this issue. I leave a message  when I have a new discovery or idea.

Thank you for your help and patience.

Yusheng
