### ISSUE TITLE
Notes running on Mac / OSX and Python3

### ISSUE THREAD

**Issue by mapmeld** [linuxscout/arramooz#16]
My current code is a bit of a hack, so I don't know if you would like this as a PR. But here are my notes for running it on my current machine

- Edited Makefile to use /Applications/LibreOffice.app/Contents/MacOS/soffice (in place of ```libreoffice``` cli)
- Replacing "python2" in Makefile with "python3"
- Removing "#!/usr/bin/python2", "print ", "has_key", ".decode()" in scripts/*
- Replace "unicode()" with "str()" in scripts/nouns/csvdict.py

**Comment by linuxscout** [comment]
Thank you very much,
can you send a PR?
