### ISSUE TITLE
So how do i generate SQL database? or alternatively can you share database files?

### ISSUE THREAD

**Issue by MonsterMMORPG** [linuxscout/arramooz#6]
I would like to generate entire SQL database

which script do i need to run and how?

or maybe you can share somewhere entire database files

**Comment by MonsterMMORPG** [comment]
ok i found it was here : https://sourceforge.net/projects/arramooz/files/

ty very much for such great project but i see number of words is pretty low

meanwhile, the spellchecker has so many words over 500k

**Comment by linuxscout** [comment]
ok, 
The spell checker has more inflected words, (forms with affixes) in order or facilitate spellchecking process.
Arramooz contains lexical words as dictionary entries.
