### ISSUE TITLE
الإعراب

### ISSUE THREAD

**Issue by AsimNet** [linuxscout/arramooz#9]
السلام عليكم ورحمة الله وبركاته 

باستخدام هذا المشروع، هل نستطيع اعراب الجمل؟

**Comment by linuxscout** [comment]
ممكن استعماله كقاموس للتحليل الصرفي، ومن ثمّ يمكن استخلاص كل العلاقات الإعرابية
ألق نظرة على موقع
http://tahadz.com/mishkal
